[env]
_.python.venv = { path = ".venv", create = true }

[tools]
uv = "0.11.6"
python = "3.14.4"
gh = "2.89.0"

[settings]
experimental = true

[hooks]
postinstall = "uv sync --only-group build --frozen"

[tasks."test:integration"]
description = "Run integration tests"
run = "invoke test.integration"

[tasks.test]
description = "Run all tests"
depends = ["test:integration"]

[tasks."version:read"]
description = "Read plugin version"
run = "invoke version.read"

[tasks."version:write"]
description = "Write plugin version"
run = "invoke version.write"

[tasks."version:bump"]
description = "Bump plugin version"
run = "invoke version.bump"

[tasks."prerelease"]
description = "Create prerelease version of library"
run = "invoke prerelease"

[tasks."release"]
description = "Create release version of library"
run = "invoke release"
