[package]
name = "accelerator-collaboration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "The collaboration pr base-repo|update-body sub-binary."

[lints]
workspace = true

[[bin]]
name = "accelerator-collaboration"
path = "src/main.rs"

[dependencies]
collaboration = { path = "../collaboration" }
github = { path = "../github" }
vcs = { path = "../vcs" }
vcs-adapters = { path = "../vcs-adapters" }
config = { path = "../config" }
config-adapters = { path = "../config-adapters" }
kernel = { path = "../kernel" }
clap = { workspace = true }
tokio = { workspace = true }
http = "1"

[dev-dependencies]
tempfile = { workspace = true }
