//! Emits the `version` build metadata via vergen and copies the committed
//! release public key into `OUT_DIR` for the launcher to `include_str!`.
//!
//! vergen's `fail_on_error()` is intentionally not called: a git-less or shallow
//! build degrades to a placeholder rather than failing to compile.

use std::error::Error;
use std::path::Path;

use vergen_gitcl::{BuildBuilder, CargoBuilder, Emitter, GitclBuilder};

const SHORT_SHA: bool = false;

fn main() -> Result<(), Box<dyn Error>> {
    embed_release_public_key()?;
    embed_expected_tree_digests()?;

    let build = BuildBuilder::default().build_timestamp(true).build()?;
    let cargo = CargoBuilder::default().target_triple(true).build()?;
    let gitcl = GitclBuilder::default().sha(SHORT_SHA).build()?;
    Emitter::default()
        .add_instructions(&build)?
        .add_instructions(&cargo)?
        .add_instructions(&gitcl)?
        .emit()?;
    Ok(())
}

fn embed_release_public_key() -> Result<(), Box<dyn Error>> {
    // CARGO_MANIFEST_DIR is cli/launcher; the committed key is at the repo root.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let source =
        Path::new(&manifest_dir).join("../../keys/accelerator-release.pub");
    let out_dir = std::env::var("OUT_DIR")?;
    let destination = Path::new(&out_dir).join("release.pub");

    let key = std::fs::read(&source).map_err(|error| {
        format!(
            "cannot read the release public key at {}: {error}",
            source.display()
        )
    })?;
    std::fs::write(&destination, key)?;
    println!("cargo:rerun-if-changed={}", source.display());
    Ok(())
}

/// Read the committed `pins.toml` and emit the launcher's expected
/// `(artifact, platform) -> archive_sha256` map as generated source.
///
/// Embedded at build time from the reviewed anchor rather than read from the
/// environment: a build-time environment variable would go stale silently,
/// because `cargo:rerun-if-env-changed` appears nowhere in this repository, so a
/// binary once built with a substituted digest would keep it after the variable
/// was unset. `rerun-if-changed` on the file gives the rebuild the env approach
/// could not.
fn embed_expected_tree_digests() -> Result<(), Box<dyn Error>> {
    use std::fmt::Write as _;
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let source = Path::new(&manifest_dir).join("../../pins.toml");
    let text = std::fs::read_to_string(&source).map_err(|error| {
        format!("cannot read {}: {error}", source.display())
    })?;
    let pins: toml::Value = text.parse()?;

    let assembled = pins
        .get("assembled_sha256")
        .and_then(toml::Value::as_table)
        .ok_or("pins.toml has no [assembled_sha256] table")?;

    let mut rows: Vec<(String, String, String)> = Vec::new();
    for (artifact, platforms) in assembled {
        let platforms = platforms
            .as_table()
            .ok_or("an assembled_sha256 entry is not a table")?;
        for (platform, digest) in platforms {
            let digest = digest
                .as_str()
                .ok_or("an assembled_sha256 digest is not a string")?;
            rows.push((artifact.clone(), platform.clone(), digest.to_owned()));
        }
    }
    rows.sort();

    let mut generated = String::from(
        "// Generated by build.rs from pins.toml; do not edit.\n\
         pub(crate) const EXPECTED_TREE_DIGESTS: &[(&str, &str, &str)] = &[\n",
    );
    for (artifact, platform, digest) in rows {
        writeln!(
            generated,
            "    (\"{artifact}\", \"{platform}\", \"{digest}\"),"
        )?;
    }
    generated.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR")?;
    std::fs::write(Path::new(&out_dir).join("tree_pins.rs"), generated)?;
    println!("cargo:rerun-if-changed={}", source.display());
    Ok(())
}
