[package]
name = "design"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
kernel = { path = "../kernel" }
base64 = { workspace = true }
percent-encoding = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
