[package]
name = "work"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
corpus = { path = "../corpus" }
kernel = { path = "../kernel" }
tracker = { path = "../tracker" }

[dev-dependencies]
serde_json = { workspace = true }
